//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        public string BookaName { get; set; }
        public string BookSubTitle { get; set; }
        public string BookAuthor { get; set; }
        public string BookImg { get; set; }
        public string BookDesc { get; set; }
        public int BookQty { get; set; }
        public string BookCat { get; set; }
        public string Dept { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public System.DateTime ModifiedDt { get; set; }
    }
}
