//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public string StudentId { get; set; }
        public string StudentName { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
        public int YOJ { get; set; }
    }
}
