//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentOrder
    {
        public int OrderID { get; set; }
        public string StudentId { get; set; }
        public string BookName { get; set; }
        public string BookAuthor { get; set; }
        public System.DateTime OrderDt { get; set; }
        public string TimeSlot { get; set; }
        public int ActiveOrder { get; set; }
    }
}
